base/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name='base'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('thankyou/', views.thankyou, name='thankyou'),
    path('about/', views.about, name='about'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)

paulwebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]

base/models.py
from django.db import models

# Create your models here.

base/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

base/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.template.loader import render_to_string

from .forms import ContactForm

def index(request):
    return render(request, 'base/index.html')

def thankyou(request):
    return render(request, 'base/thankyou.html')

def about(request):
    return render(request, 'base/about.html')

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            content = form.cleaned_data['content']

            html = render_to_string('base/emails/contactform.html', {
                'name':name,
                'email':email,
                'content':content
            })

            send_mail('The contact form subject', 'This is the message', 'noreply@code.com', ['picslotoguitar@gmail.com'], html_message=html)

            return redirect('/thankyou/')
    else:
        print('error')
        form = ContactForm()
    
    return render(request, 'base/contact.html', {'form':form})

base/templates/base/about.html
{# Load the tag library #} {% load bootstrap5 %} {# Load CSS and JavaScript #}
{% bootstrap_css %} {% bootstrap_javascript %} {% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Google tag (gtag.js) -->
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=G-CP5YN235VZ"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag("js", new Date());

      gtag("config", "G-CP5YN235VZ");
    </script>
    <!-- End Google tag (gtag.js) -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    {% comment %}
    <link rel="stylesheet" href="{% static 'base/css/style.css' %}" />
    {% endcomment %}
    <link rel="stylesheet" href="{% static 'base/css/about.css' %}" />
    <title>About</title>
  </head>
  <body>
    <header>{% include 'base/navbar.html' %}</header>
    <main>
      <div class="left-container container">
        <h2>Welcome to my musical world!</h2>
        <hr />
        <p>
          I am a proficient musician and songwriter based in Long Beach,
          California. With over 20 years of experience in the music industry, I
          have honed my skills and developed a unique sound that has garnered
          attention from audiences across the United States. My Latin-American
          influenced music has captured the hearts of listeners in numerous
          cities, and I am highly sought after for both solo performances and as
          a member of the soul band
          <a href="https://www.instagram.com/theintuitions">Intuitions</a>,
          where I play bass and provide backup vocals.
        </p>
        <p>
          To stay up to date on my latest album releases and upcoming show
          dates, be sure to follow me on social media
          <a href="https://www.instagram.com/picksalot/">@picksalot</a>. You can
          also stream my music on all major platforms, including my new single
          <a href="https://open.spotify.com/album/2NjdQYmz1wG1F2Pvia50cz"
            >"You"</a
          >.
        </p>
        <p>
          If you are interested in booking me for a performance or have any
          other inquiries, please utilize the link below to contact me. Don't
          miss out on the chance to experience my dynamic music live!
        </p>

        <a class="btn btn-primary btn-lg" href="{% url 'base:contact' %}"
          >Contact Me</a
        >
      </div>
      <div class="right-container container">
        <h1>Hi, I'm Paul</h1>
        <div class="inner-container">
          <img src="{% static 'base/images/paul-about.png' %}" />
        </div>
      </div>
    </main>
  </body>
</html>

base/templates/base/contact.html
{# Load the tag library #} {% load bootstrap5 %} {# Load CSS and JavaScript #}
{% bootstrap_css %} {% bootstrap_javascript %} {# Display
django.contrib.messages as Bootstrap alerts #} {% bootstrap_messages %} {% load
static %}

<!DOCTYPE >
<html lang="en">
  <head>
    <!-- Google tag (gtag.js) -->
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=G-CP5YN235VZ"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag("js", new Date());

      gtag("config", "G-CP5YN235VZ");
    </script>
    <!-- End Google tag (gtag.js) -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'base/css/contact.css' %}" />
    <title>Contact Me</title>
  </head>
  <body>
    <header>{% include 'base/navbar.html' %}</header>

    <main>
      <div class="contact-text">
        <h1>Get In Touch With Me</h1>

        <p>
          Thank you for visiting my website! I am a musician based in Long
          Beach, CA and I offer a range of services.
        </p>

        <p>
          To book me for a gig or to inquire about my services, please use the
          form or contact me at the following email address:
        </p>

        <p>
          Email:
          <a class="email" href="mailto:picslotoguitar@gmail.com"
            >picslotoguitar@gmail.com</a
          >
        </p>
      </div>

      <div class="form-container">
        <form method="POST" action="." class="form">
          <h2 id="form-title">Contact Form</h2>
          {% csrf_token %} {% bootstrap_form form %} {% bootstrap_button
          "Submit" button_type="submit" button_class="btn-primary" size="lg" %}
        </form>
      </div>
    </main>
  </body>
</html>

base/templates/base/index.html
{# Load the tag library #} {% load bootstrap5 %} {# Load CSS and JavaScript #}
{% bootstrap_css %} {% bootstrap_javascript %} {% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Google tag (gtag.js) -->
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=G-CP5YN235VZ"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag("js", new Date());

      gtag("config", "G-CP5YN235VZ");
    </script>
    <!-- End Google tag (gtag.js) -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="{% static 'base/css/style.css' %}" />
    <title>Paul Anthony Garcia</title>
  </head>
  <body>
    <header>{% include 'base/navbar.html' %}</header>

    <main class="hero">
      <div class="overlay">
        <div class="hero-container">
          <h1 class="logo">PAUL ANTHONY GARCIA</h1>

          <a href="{% url 'base:contact' %}" class="btn btn-primary"
            >CONTACT ME</a
          >
        </div>
      </div>
    </main>

    <section class="main">
      <div class="main-container">
        <div class="thumbnail-container">
          <h3>NEW VIDEO OUT NOW</h3>
          <a href="https://youtu.be/9gCAlwJphFY"
            ><img
              class="img-fluid contain"
              src="{% static 'base/images/enough-thumbnail.png' %}"
              alt="thumbnail"
          /></a>
          <a href="https://youtu.be/9gCAlwJphFY" class="btn watch-btn">WATCH</a>
        </div>
        <h2>NEW ALBUM "YOU"</h2>
        <a href="https://open.spotify.com/artist/1SxbAufa9tba1kQaAsMqqK">
          <img src="{% static 'base/images/album.png' %}" alt="album 'You'" />
        </a>
        <a
          href="https://open.spotify.com/artist/1SxbAufa9tba1kQaAsMqqK"
          class="btn btn-primary"
          >LISTEN</a
        >
        <div class="tip-container container">
          <h3>MY VENMO AND CASH-APP</h3>
          <div class="tip-container-icons">
            <a href="https://account.venmo.com/u/Picksalot"
              ><i class="fa-brands fa-square-vimeo fa-4x"></i
            ></a>
            <a href="https://cash.app/$Picksalot" class="cash-app"
              ><img
                id="cash-app"
                src="{%static 'base/images/cashapp.svg' %}"
                style="width: 60px"
            /></a>
          </div>
        </div>
      </div>
    </section>

    <footer class="footer">
      <div class="footer-container">
        <hr class="top-line" />
        <a href="https://linktr.ee/Picksalot">
          <h3>FOLLOW</h3>
        </a>
        <hr class="bottom-line" />
        <div class="icons">
          <a href="https://www.instagram.com/picksalot/">
            <i class="fa-brands fa-instagram fa-2x"></i>
          </a>
          <a href="https://www.reddit.com/user/picslotoguitar">
            <i class="fa-brands fa-reddit fa-2x"></i>
          </a>
          <a href="https://www.youtube.com/@PaulPicksalot">
            <i class="fa-brands fa-youtube fa-2x"></i>
          </a>
          <a href="https://open.spotify.com/artist/1SxbAufa9tba1kQaAsMqqK">
            <i class="fa-brands fa-spotify fa-2x"></i>
          </a>
          <a href="https://www.tiktok.com/@picksalot">
            <i class="fa-brands fa-tiktok fa-2x"></i>
          </a>
        </div>
      </div>
    </footer>
  </body>
</html>

base/templates/base/navbar.html
{% load static %}

<head>
  <link rel="stylesheet" href="{% static 'base/css/navbar.css' %}">
</head>

<nav id="navbar" class="navbar navbar-expand-lg bg-body-tertiary navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'base:index' %}">PICKSALOT</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'base:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base:contact' %}">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

base/templates/base/thankyou.html
{# Load the tag library #} {% load bootstrap5 %} {% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Google tag (gtag.js) -->
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=G-CP5YN235VZ"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag("js", new Date());

      gtag("config", "G-CP5YN235VZ");
    </script>
    <!-- End Google tag (gtag.js) -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="{% static 'base/css/thankyou.css' %}" />
    <title>Thank You!</title>
  </head>

  <body>
    <div>
      <h1>Thank You!</h1>
      <p>
        Thank you for your message. Your email has been sent successfully and I
        will get back to you as soon as possible.
      </p>
      <a href="/" class="btn btn-primary">Return to Homepage</a>
    </div>
  </body>
</html>